### ISSUE TITLE
findReplaceDialog

### ISSUE THREAD

**Issue by osysltd** [microsoft/Office365APIEditor#17]
Dear Ryutaro,
I haven't dig into the code since the last commits, but findReplaceDialog stopped working for me (Ctrl +F for example)
Much appreciate If you could quickly take a look

https://github.com/microsoft/Office365APIEditor/blob/a0c5b0ef703bfdec61bb189cf2a0f5986e54ecb3/Office365APIEditor/UI/RequestForm.cs#L1987

**Comment by rykoma** [comment]
@osysltd 

If my understanding is correct, only findReplaceDialog for scintilla_RequestBody does not work, right? I think findReplaceDialog for scintilla_ResponseBody is working.

I didn't enabled findReplaceDialog for scintilla_RequestBody intentionally, because there was a problem when I merged ScintillaNET and ScintillaNET FindReplaceDialog into our source code. And, I thought findReplaceDialog is not needed for scintilla_RequestBody.

Do you think that it's better to enable findReplaceDialog for scintilla_RequestBody?

**Comment by osysltd** [comment]
@rykoma 

Sorry for the late reply, too much of stuff recently. 
Yep, as an example thinking of a search each time seeing the huge JSON of the O365 Management API DLP.ALL event. Scrolling is a mess.

I will try to make PR shortly.
