### ISSUE TITLE
Office 365 reports

### ISSUE THREAD

**Issue by karampuri** [Microsoft/Office365APIEditor#4]
Hi

How to get the reports usage details like Email activity and Inactive users etc.using which rest API for python.

**Comment by rykoma** [comment]
How about Office 365 Reporting web service?
https://msdn.microsoft.com/en-us/library/office/jj984325.aspx

You can use MailboxUsageDetail to check if the mailbox is inactive.



 Example using PowerShell:

> λ $result = Invoke-RestMethod -Method get -Uri "https://reports.office365.com/ecp/reportingwebservice/reporting.svc/MailboxUsageDetail" -Credential $cred | select -ExpandProperty content

> C:\
> λ $result | select -First 10 | select @{e={$_.properties.UserName};n="UserName"},@{e={$_.properties.MailboxSize.InnerTe xt};n="MailboxSize"},@{e={$_.properties.IsInactive.InnerText};n="IsInactive"}

> UserName         MailboxSize IsInactive
> \--------         ----------- ----------
> ExoDiscovery01   52428800    false
> ExoEnglishUser01 104857600   false
> ExoEwsAdmin01    52428800    true
> EXOIMTEST01      104857600   false
> ExoRoom01        52428800    true
> ExoRoom02        52428800    true
> ExoShared01      52428800    false
> ExoUser01        104857600   false
> ExoUser02        104857600   false
> ExoUser03        104857600   false


Since there are many other reports on the web service, so please check if there is a report you need.
https://msdn.microsoft.com/EN-US/library/office/jj984342.aspx

If you don't know how to use it, I recommnend that you open a Microsoft support ticket.
Unfortunately, Office365APIEditor currently does not support this web service.

**Comment by rykoma** [comment]
Close this issue due to no response.
