### ISSUE TITLE
prereqs just dont work

### ISSUE THREAD

**Issue by EricZimmerman** [Microsoft/Office365APIEditor#5]
why are there like 900 different versions of documentation, examples (that don't work) and all other manner of useless stuff as it relates to actually using this stuff?

you say to create an app at https://apps.dev.microsoft.com/, then link to a tutorial that is TOTALLY DIFFERENT THAN HOW YOU DO IT AT THE URL PROVIDED!

Turns out you just need to add Native Application and it seems to work.

why someone there cannot make a NuGet package that lets me supply a username and a password to get what I need to make use of the APIs is beyond me =(

**Comment by EricZimmerman** [comment]
also, how do you fix this:

Please ask an admin to grant permission to this app before you can use it. 

i want the app to work for ALL users in my instance.

is that some magic incantation of this URL?

https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?

**Comment by rykoma** [comment]
Hello Eric,

> why are there like 900 different versions of documentation, examples (that don't work) and all other manner of useless stuff as it relates to actually using this stuff?

I'm afraid, what are you talking about?
About this repro?


> you say to create an app at https://apps.dev.microsoft.com/, then link to a tutorial that is TOTALLY DIFFERENT THAN HOW YOU DO IT AT THE URL PROVIDED!

I'll update the UI and tutorials of this repro at a later date.
(I'm afraid, it is difficult to update in a timely manner, because there are many ways to register your apps and UI of each portals change frequently.)


> why someone there cannot make a NuGet package that lets me supply a username and a password to get what I need to make use of the APIs is beyond me =(

You might be able to use grant_type=password.
If you could confirm that this method is available, you can implement your own library.
But I don't recommend this method because we can't use multi factor authentication.

This page might be helpful.
https://github.com/nordvall/TokenClient/issues/1


> Please ask an admin to grant permission to this app before you can use it.
> i want the app to work for ALL users in my instance.

You mean "Admin consent"?
This page might be helpful.
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview


Office365APIEditor has a feature of Admin consent.
Go to [Tools] - [New Editor] - [File] - [New Access Token] - [v1.0 Endpoint] - [I need to complete ADMIN CONSENT before acquiring access token].


If you have questions or feedback about Office365APIEditor, feel free to post issues.
If you have questions or feedback about Azure Active Directory or Microsoft Graph, you should go to StackOverFlow or open a support ticket of Microsoft.

**Comment by rykoma** [comment]
Close this issue due to no response.
